plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    site: datadoghq.com
    apiKey: xxxxxxx

service: xxxxx
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: sit
  tags:
    env: sit
    service: xxxxx
    version: '1.0'

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
