plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    site: datadoghq.com
    apiKey: xxxxxxx
    ## This parameter is required when collecting telemetry using the Datadog Lambda Extension. Alternatively, you can also set the DATADOG_API_KEY environment variable in your deployment environment.

service: xxxxx
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: sit
  tags:
    env: sit
    service: xxxxx
    version: '1.0'

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
