apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  labels:
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "express-app"
    tags.datadoghq.com/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      annotations:
        ad.datadoghq.com/tags: '{"service: "express-app"}'
        # This is needed to specify the dd-lib-js-init container image tag in use
        # https://console.cloud.google.com/gcr/images/datadoghq/GLOBAL/dd-lib-js-init
        # ie: latest is the image tag for whatever happens to be the latest version
        admission.datadoghq.com/js-lib.version: "latest"
      labels:
        app: express-app
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "express-app"
        tags.datadoghq.com/version: "1.0"
        # This line is necessary when using `mutateUnlabelled: false`:
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
      - name: express-app
        image: not-a-real-dockerhub-this-is-local/express:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DD_TRACE_DEBUG
          value: 'true'


---
apiVersion: v1
kind: Service
metadata:
  name: express-app
spec:
  selector:
    app: express-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
  type: LoadBalancer
