apiVersion: v1
kind: Pod
metadata:
  annotations:
    admission.datadoghq.com/js-lib.version: "latest"        <<<<<<<<<
  labels:
    admission.datadoghq.com/enabled: "true"                   <<<<<<<<<
    app: express-app
    tags.datadoghq.com/env: "dev"                             <<<<<<<<<
    tags.datadoghq.com/service: "express-app"                 <<<<<<<<<
    tags.datadoghq.com/version: "1.0"                         <<<<<<<<<
  name: adservice-7b85b77cd6-5x2rn
  namespace: default
spec:
  containers:
  - name: express-app
    image: not-a-real-dockerhub-this-is-local/express:1.0
    imagePullPolicy: Never
    ports:
    - containerPort: 3000
    env:
    - name: DD_TRACE_DEBUG
    value: 'true'
